zeo:
  build: zeo
  user: 1000
  volumes_from:
   - data
#
client:
  restart: always
  build: client
  user: 1000
  links:
   - zeo:zeo
  ports:
   - "8881:8081"
  volumes_from:
   - data

www2:
  restart: always
  build: client
  user: 1000
  links:
   - zeo:zeo
  ports:
   - "8880:8081"
  volumes_from:
   - data
data:
  build: data
  user: 1000
varnish:
  restart: always
  build: varnish
  links:
   - app:instance1
   - app:instance2
  ports:
   - "8080:80"
