apache:
  image: eeacms/apache
  links:
    - haproxy
  ports:
    - "7070:80"
  env_file:
    - apache.env
  restart: always

haproxy:
  image: eeacms/haproxy:1.5
  links:
    - www1
    - www2
  restart: always

www1:
  image: eeacms/cynin
  volumes_from:
    - data
  links:
    - zeo
    - postfix
  command: bin/www1 console
  restart: always

www2:
  image: eeacms/cynin
  volumes_from:
    - data
  links:
    - zeo
    - postfix
  command: bin/www1 console
  restart: always

zeo:
  image: eeacms/cynin
  volumes_from:
    - data
  command: bin/zeoserver fg
  restart: always

postfix:
  image: eeacms/postfix:eionet
  volumes:
    - /etc/localtime:/etc/localtime:ro
  env_file:
    - .postfix.secret
  restart: always

data:
  build: data
  volumes:
    - /var/local/community.eea.europa.eu/var/filestorage
    - /var/local/community.eea.europa.eu/var/blobstorage
