apache:
  image: eeacms/apache
  restart: always
  links:
  - haproxy
  ports:
  - "80:80"
  environment:
  - SERVER_ADMIN=helpdesk@eionet.europa.eu
  - SERVER_NAME=community.eea.europa.eu
  - RewriteRule=^/(.*) http://haproxy/VirtualHostBase/http/community.eea.europa.eu:80/cynin/VirtualHostRoot/$1 [P,L]

haproxy:
  image: eeacms/haproxy:1.5
  restart: always
  links:
  - www1
  - www2

www1:
  image: eeacms/cynin
  restart: always
  links:
  - zeo
  - postfix
  volumes_from:
  - data
  command: bin/www1 console

www2:
  image: eeacms/cynin
  restart: always
  links:
  - zeo
  - postfix
  volumes_from:
  - data
  command: bin/www1 console

zeo:
  image: eeacms/cynin
  restart: always
  volumes_from:
  - data
  command: bin/zeoserver fg

postfix:
  image: eeacms/postfix:eionet
  restart: always
  volumes:
  - /etc/localtime:/etc/localtime:ro
  env_file:
  - .postfix.secret

data:
  build: data
  volumes:
  - /var/local/community.eea.europa.eu/var/filestorage
  - /var/local/community.eea.europa.eu/var/blobstorage
